/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import accesoDatos.BarcosDAO;
import accesoDatos.SociosDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetosNegocios.Barco;
import objetosNegocios.Socio;

/**
 *
 * @author miran
 */
public class FrmMenu extends javax.swing.JFrame {

    private SociosDAO sociosDAO;
    private BarcosDAO barcosDAO;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("FrmMenu");
        sociosDAO = new SociosDAO();
        barcosDAO = new BarcosDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        PanelImagenes = new javax.swing.JPanel();
        imgBarco = new javax.swing.JLabel();
        capi = new javax.swing.JLabel();
        rudder = new javax.swing.JLabel();
        lblBarco = new javax.swing.JLabel();
        lbSalidas = new javax.swing.JLabel();
        lbSocios = new javax.swing.JLabel();
        lbSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        PanelImagenes.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagenes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        imgBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boteAzul.jpg"))); // NOI18N
        imgBarco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBarcoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgBarcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgBarcoMouseExited(evt);
            }
        });

        capi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capiAzul.png"))); // NOI18N
        capi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                capiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                capiMouseExited(evt);
            }
        });

        rudder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rudderAzulBlue.png"))); // NOI18N
        rudder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rudderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rudderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rudderMouseExited(evt);
            }
        });

        lblBarco.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblBarco.setForeground(new java.awt.Color(0, 51, 102));
        lblBarco.setText("Barcos");
        lblBarco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarcoMouseClicked(evt);
            }
        });

        lbSalidas.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lbSalidas.setForeground(new java.awt.Color(0, 51, 102));
        lbSalidas.setText("Salidas");
        lbSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSalidasMouseClicked(evt);
            }
        });

        lbSocios.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lbSocios.setForeground(new java.awt.Color(0, 51, 102));
        lbSocios.setText("Socios");
        lbSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSociosMouseClicked(evt);
            }
        });

        lbSalir.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lbSalir.setForeground(new java.awt.Color(204, 0, 0));
        lbSalir.setText("Salir");
        lbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSalirMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("MENÚ");

        javax.swing.GroupLayout PanelImagenesLayout = new javax.swing.GroupLayout(PanelImagenes);
        PanelImagenes.setLayout(PanelImagenesLayout);
        PanelImagenesLayout.setHorizontalGroup(
            PanelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImagenesLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lbSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSalidas)
                .addGap(98, 98, 98))
            .addGroup(PanelImagenesLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(capi)
                .addGroup(PanelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImagenesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(imgBarco)
                        .addGap(56, 56, 56))
                    .addGroup(PanelImagenesLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(rudder)
                .addGap(74, 74, 74))
            .addGroup(PanelImagenesLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel2)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImagenesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSalir)
                .addGap(22, 22, 22))
        );
        PanelImagenesLayout.setVerticalGroup(
            PanelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImagenesLayout.createSequentialGroup()
                .addGroup(PanelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImagenesLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(PanelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelImagenesLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(rudder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSalidas))
                            .addGroup(PanelImagenesLayout.createSequentialGroup()
                                .addComponent(capi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSocios))))
                    .addGroup(PanelImagenesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(91, 91, 91)
                        .addComponent(imgBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBarco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(lbSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(PanelImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelImagenes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, -1, 610));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, -1, 660));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 660));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 660));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 660));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 660));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 660));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 660));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 660));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 660));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseClicked
          int salir = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "¡¡Atención!!", JOptionPane.WARNING_MESSAGE);
        if (salir == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lbSalirMouseClicked

    private void capiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capiMouseClicked
     
        FrmSocios socios = new FrmSocios();
        this.dispose();
        socios.setVisible(true);
     
    }//GEN-LAST:event_capiMouseClicked

    private void imgBarcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBarcoMouseClicked
        if (!haySocios()) {
            FrmBarcos barco = new FrmBarcos();
            this.dispose();
            barco.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún socio", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_imgBarcoMouseClicked

    private void rudderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rudderMouseClicked
        if(!hayBarcos()){ 
        FrmSalidas salidas = new FrmSalidas();
        this.dispose();
        salidas.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existe ningun barco", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rudderMouseClicked

    private void capiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capiMouseExited
           capi.setIcon(new ImageIcon("imagenes\\capiAzul.png"));
       lbSocios.setFont(new Font("Ebrima", Font.BOLD, 22));
         lbSocios.setForeground(new Color(0,51,102));
    }//GEN-LAST:event_capiMouseExited

    private void capiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capiMouseEntered
        capi.setIcon(new ImageIcon("imagenes\\capiRojelio.png"));
       lbSocios.setFont(new Font("Ebrima", Font.BOLD, 30));
       lbSocios.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_capiMouseEntered

    private void imgBarcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBarcoMouseEntered
       imgBarco.setIcon(new ImageIcon("imagenes\\boatAzul.png"));
       lblBarco.setFont(new Font("Ebrima", Font.BOLD, 30));
       lblBarco.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_imgBarcoMouseEntered

    private void imgBarcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBarcoMouseExited
        imgBarco.setIcon(new ImageIcon("imagenes\\boatRojo.png"));
       lblBarco.setFont(new Font("Ebrima", Font.BOLD, 22));
       lblBarco.setForeground(new Color(0,51,102));
    }//GEN-LAST:event_imgBarcoMouseExited

    private void rudderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rudderMouseEntered
       rudder.setIcon(new ImageIcon("imagenes\\rudderRedRojo.png"));
       lbSalidas.setFont(new Font("Ebrima", Font.BOLD, 30));
       lbSalidas.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_rudderMouseEntered

    private void rudderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rudderMouseExited
        rudder.setIcon(new ImageIcon("imagenes\\rudderAzulBlue.png"));
       lbSalidas.setFont(new Font("Ebrima", Font.BOLD, 22));
       lbSalidas.setForeground(new Color(0,51,102));
    }//GEN-LAST:event_rudderMouseExited

    private void lbSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseEntered
        lbSalir.setFont(new Font("Ebrima", Font.BOLD, 30));
    }//GEN-LAST:event_lbSalirMouseEntered

    private void lbSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseExited
        lbSalir.setFont(new Font("Ebrima", Font.BOLD, 22));
    }//GEN-LAST:event_lbSalirMouseExited

    private void lbSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSociosMouseClicked
        FrmSocios socios = new FrmSocios();
        this.dispose();
        socios.setVisible(true);
    }//GEN-LAST:event_lbSociosMouseClicked

    private void lblBarcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarcoMouseClicked
        if (!haySocios()) {
            FrmBarcos barco = new FrmBarcos();
            this.dispose();
            barco.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún socio", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblBarcoMouseClicked

    private void lbSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalidasMouseClicked
          if(!hayBarcos()){ 
        FrmSalidas salidas = new FrmSalidas();
        this.dispose();
        salidas.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existe ningun barco", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lbSalidasMouseClicked

    
    private boolean haySocios(){
        List<Socio> lista = sociosDAO.consultar("");
     //   System.out.println(lista);
        if(lista.isEmpty()){            
            return true;
        }        
        return false;
    }
    
    private boolean hayBarcos(){
        List<Barco> lista = barcosDAO.consultar("");
     
        if(lista.isEmpty()){            
            return true;
        }        
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelImagenes;
    private javax.swing.JLabel capi;
    private javax.swing.JLabel imgBarco;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbSalidas;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JLabel lbSocios;
    private javax.swing.JLabel lblBarco;
    private javax.swing.JLabel rudder;
    // End of variables declaration//GEN-END:variables
}
