/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import accesoDatos.BarcosDAO;
import accesoDatos.SalidasDAO;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosNegocios.Barco;
import objetosNegocios.Salida;

/**
 *
 * @author miran
 */
public class FrmSalidas extends javax.swing.JFrame {

    BarcosDAO barcosDAO;
    SalidasDAO salidasDAO;

    /**
     * Creates new form FrmSalida
     */
    public FrmSalidas() {
        initComponents();
        this.setTitle("frmSalida");
        this.setLocationRelativeTo(null);
        barcosDAO = new BarcosDAO();
        salidasDAO = new SalidasDAO();
        this.cargarTabla();
        this.dtpSalidas.setDateTimePermissive(LocalDateTime.now());
        this.llenarCbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoAzul = new javax.swing.JPanel();
        Blanco1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdSalida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboxBarcos = new javax.swing.JComboBox<>();
        dtpSalidas = new com.github.lgooddatepicker.components.DateTimePicker();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        FonfoBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalidas = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        barcos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoAzul.setBackground(new java.awt.Color(0, 51, 102));

        Blanco1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de salidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel1.setText("ID");
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));

        txtIdSalida.setEditable(false);
        txtIdSalida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setText("Fecha y Hora");
        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));

        jLabel3.setText("Destino");
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));

        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDestino.setToolTipText("");
        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });
        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestinoKeyTyped(evt);
            }
        });

        jLabel4.setText("Barcos");
        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));

        cboxBarcos.setEditable(true);
        cboxBarcos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboxBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBarcosActionPerformed(evt);
            }
        });

        dtpSalidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btGuardar.setText("Guardar");
        btGuardar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 51, 102));
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(0, 51, 102));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addGap(126, 126, 126)
                        .addComponent(btCancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dtpSalidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                        .addComponent(cboxBarcos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dtpSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboxBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btCancelar))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        FonfoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        FonfoBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsquedas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        txtBuscar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 51, 102));

        btEliminar.setText("Eliminar");
        btEliminar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btEliminar.setForeground(new java.awt.Color(0, 51, 102));
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        tblSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha y Hora", "Destino", "Barco", "Socio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSalidas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(tblSalidas);

        btEditar.setText("Editar");
        btEditar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btEditar.setForeground(new java.awt.Color(0, 51, 102));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(0, 51, 102));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btSalir.setForeground(new java.awt.Color(0, 51, 102));
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FonfoBusquedaLayout = new javax.swing.GroupLayout(FonfoBusqueda);
        FonfoBusqueda.setLayout(FonfoBusquedaLayout);
        FonfoBusquedaLayout.setHorizontalGroup(
            FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FonfoBusquedaLayout.createSequentialGroup()
                .addGroup(FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FonfoBusquedaLayout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FonfoBusquedaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(FonfoBusquedaLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FonfoBusquedaLayout.setVerticalGroup(
            FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FonfoBusquedaLayout.createSequentialGroup()
                .addGroup(FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FonfoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Blanco1Layout = new javax.swing.GroupLayout(Blanco1);
        Blanco1.setLayout(Blanco1Layout);
        Blanco1Layout.setHorizontalGroup(
            Blanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Blanco1Layout.createSequentialGroup()
                .addGroup(Blanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Blanco1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(FonfoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Blanco1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Blanco1Layout.setVerticalGroup(
            Blanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Blanco1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FonfoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        barcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salidaBlanco.png"))); // NOI18N
        barcos.setText("Salidas");
        barcos.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        barcos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flechaBlanco.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homeBlanco.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoAzulLayout = new javax.swing.GroupLayout(FondoAzul);
        FondoAzul.setLayout(FondoAzulLayout);
        FondoAzulLayout.setHorizontalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Blanco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(barcos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );
        FondoAzulLayout.setVerticalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addGroup(FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoAzulLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(barcos))
                    .addGroup(FondoAzulLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Blanco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        this.cagarSalida();
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        if (validar()) {
            if (txtIdSalida.getText().isEmpty()) {
                this.guardar();
            } else {
                this.actualizar();
            }
            this.cargarTabla();
        }else{
            JOptionPane.showMessageDialog(this, "No se deben dejar campos vacíos","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if(txtBuscar.getText().isEmpty()){
            this.cargarTabla();
        }else{
            this.isID();
        }
        this.limpiar();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       FrmMenu menu= new FrmMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        FrmMenu menu= new FrmMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        this.eliminar();
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "¡¡Atención!!", JOptionPane.WARNING_MESSAGE);
        if (salir == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSalirActionPerformed

    private void txtDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyTyped
        if (txtDestino.getText().length() == 100) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtDestinoKeyTyped

    private void cboxBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBarcosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxBarcosActionPerformed

    private boolean validar(){
        if(this.dtpSalidas.datePicker.getText().isEmpty() ||this.dtpSalidas.timePicker.getText().isEmpty()|| this.txtDestino.getText().isEmpty() || this.cboxBarcos.getSelectedIndex()==0 ){
           
            return false;
        }
        return true;
    }
    
    private void guardar() {
        Timestamp t = this.obtenerFecha();
        String destino = this.txtDestino.getText();
        Barco barco = (Barco) this.cboxBarcos.getSelectedItem();
        Salida salida = new Salida(t, destino, barco);
        if (salidasDAO.guardar(salida)) {
            JOptionPane.showMessageDialog(this, "Se ha guadado con éxito");
            this.limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha guadado","Error!!",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizar() {
        Integer id= Integer.parseInt(txtIdSalida.getText());
        Timestamp t = this.obtenerFecha();
        String destino = this.txtDestino.getText();
        Barco barco = (Barco) this.cboxBarcos.getSelectedItem();
        Salida salida = new Salida(id,t, destino, barco);
        if (salidasDAO.actualizar(salida)) {
            JOptionPane.showMessageDialog(this, "Se ha actualizado con éxito");
            this.limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha guadado","Error!!",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminar(){
        int fila = this.tblSalidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una salida.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblSalidas.getModel();
            Integer idSalida = (Integer) modelo.getValueAt(fila, 0);
            boolean eliminado = salidasDAO.eliminar(idSalida);
            if (eliminado == true) {
                JOptionPane.showMessageDialog(this, "Salida eliminada correctamente.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                this.cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la salida.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void cagarSalida(){
        int fila = this.tblSalidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una salida .",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblSalidas.getModel();
            Integer idSalida = (Integer) modelo.getValueAt(fila, 0);
            Salida salida = salidasDAO.consultar(idSalida);
            if (salida != null) {
                txtIdSalida.setText(String.valueOf(salida.getIdSalida()));
                this.dtpSalidas.setDateTimePermissive(salida.getFecha().toLocalDateTime());
                this.txtDestino.setText(salida.getDestino());
                this.cboxBarcos.setSelectedItem(salida.getBarco());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el animal.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }
    
    private void limpiar(){
        this.txtIdSalida.setText("");
        this.dtpSalidas.setDateTimePermissive(LocalDateTime.now());
        this.txtDestino.setText("");
        this.cboxBarcos.setSelectedIndex(0);
    }
    private Timestamp obtenerFecha(){
        //DatePicker dp= this.dtpSalidas.getDatePicker();
        ///LocalDate fecha=dp.getDate();
         //LocalTime lc =this.dtpSalidas.getTimePicker().getTime();
        //Date d= new Date(fecha.getYear()-1900, fecha.getMonthValue(), fecha.getDayOfMonth(), lc.getHour(), lc.getMinute());
        //Timestamp t= new Timestamp(d.getTime());
        //this.dtpSalidas.get     
        LocalDateTime local=this.dtpSalidas.getDateTimePermissive();
        Timestamp timestamp = Timestamp.valueOf(local);
        //Timestamp t= new Timestamp(local.getYear()-1900, local.getMonthValue(), local.getDayOfMonth(), local.getHour(), local.getMinute(),0,0);
        return timestamp;
    }
    
    private void llenarCbox() {
        Barco seleccioneP = new Barco();
        seleccioneP.setNombre("Seleccione...");
        seleccioneP.setMatricula("");
        cboxBarcos.addItem(seleccioneP);
        List<Barco> barcos = this.barcosDAO.consultar("");
        for (Barco barco : barcos) {
            cboxBarcos.addItem(barco);
        }
    }

    private void cargarTabla() {
        List<Salida> salidas = salidasDAO.consultar(txtBuscar.getText());
        if (salidas != null) {
            DefaultTableModel modelo = (DefaultTableModel) tblSalidas.getModel();
            modelo.setRowCount(0);
            for (Salida c : salidas) {
                modelo.addRow(c.toArray());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sin resultados.",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void cargarTablaID(int id) {
        Salida salida = salidasDAO.consultar(id);
        DefaultTableModel modelo = (DefaultTableModel) tblSalidas.getModel();
        modelo.setRowCount(0);
        if (salida != null) {
            modelo.addRow(salida.toArray());
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna saldia con ese ID", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void isID(){
         if (txtBuscar.getText().matches("^[0-9]*$")) {
             this.cargarTablaID(Integer.parseInt(txtBuscar.getText()));
         }else{
             this.cargarTabla();
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSalidas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSalidas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSalidas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSalidas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSalidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Blanco1;
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FonfoBusqueda;
    private javax.swing.JLabel barcos;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox<Barco> cboxBarcos;
    private com.github.lgooddatepicker.components.DateTimePicker dtpSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalidas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdSalida;
    // End of variables declaration//GEN-END:variables
}
